// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function Home(Props) {
  return React.createElement("div", undefined, React.createElement("h2", undefined, "HOME"));
}

var make = Home;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
