// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as LogoPng from "../assets/logo.png";

function str(prim) {
  return prim;
}

var logo = LogoPng;

var header = Css.style(/* :: */[
      Css.backgroundColor(Css.rgba(238, 35, 45, 1.0)),
      /* :: */[
        Css.display(Css.flexBox),
        /* :: */[
          Css.justifyContent(Css.spaceBetween),
          /* :: */[
            Css.alignItems(Css.center),
            /* [] */0
          ]
        ]
      ]
    ]);

var title = Css.style(/* :: */[
      Css.color(Css.white),
      /* :: */[
        Css.fontSize(Css.px(36)),
        /* :: */[
          Css.fontWeight(Css.bold),
          /* [] */0
        ]
      ]
    ]);

var logo$1 = Css.style(/* :: */[
      Css.width(Css.px(50)),
      /* :: */[
        Css.height(Css.px(50)),
        /* :: */[
          Css.marginLeft(Css.px(32)),
          /* [] */0
        ]
      ]
    ]);

var search_input_wrapper = Css.style(/* :: */[
      Css.marginRight(Css.px(32)),
      /* [] */0
    ]);

var search_input = Css.style(/* :: */[
      Css.marginRight(Css.px(8)),
      /* [] */0
    ]);

var Styles = /* module */[
  /* header */header,
  /* title */title,
  /* logo */logo$1,
  /* search_input_wrapper */search_input_wrapper,
  /* search_input */search_input
];

function Nav(Props) {
  return React.createElement("div", undefined, React.createElement("header", {
                  className: header
                }, React.createElement("img", {
                      className: logo$1,
                      src: logo
                    }), React.createElement("span", {
                      className: title
                    }, "Super Marvel Heroes"), React.createElement("div", {
                      className: search_input_wrapper
                    }, React.createElement("input", {
                          className: search_input,
                          placeholder: "search"
                        }), React.createElement("button", undefined, "Search"))), React.createElement("a", {
                  href: "./index.html"
                }, "Home"), React.createElement("a", {
                  href: "#"
                }, "Profile"), React.createElement("a", {
                  href: "#"
                }, "Archetype"), React.createElement("a", {
                  href: "#"
                }, "Competency"));
}

var make = Nav;

export {
  str ,
  logo ,
  Styles ,
  make ,
  
}
/* logo Not a pure module */
