// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function Profile(Props) {
  return React.createElement("div", undefined, React.createElement("h2", undefined, "PROFILE"));
}

var make = Profile;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
