// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

function str(prim) {
  return prim;
}

function App$Home(Props) {
  return React.createElement("div", undefined, React.createElement("h2", undefined, "HOME"));
}

var Home = /* module */[/* make */App$Home];

function App$Profile(Props) {
  return React.createElement("div", undefined, React.createElement("h2", undefined, "PROFILE"));
}

var Profile = /* module */[/* make */App$Profile];

var component = ReasonReact.reducerComponent("App");

function make(_children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var match = param[/* state */1][/* route */0];
              return React.createElement("div", undefined, match ? React.createElement(App$Profile, { }) : React.createElement(App$Home, { }));
            }),
          /* initialState */(function (param) {
              return /* record */[/* route : Home */0];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, _state) {
              return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

var App = /* module */[
  /* component */component,
  /* make */make
];

export {
  str ,
  Home ,
  Profile ,
  App ,
  
}
/* component Not a pure module */
