// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as Home$ReasonIsAwesome from "./Components/Home.bs.js";
import * as Profile$ReasonIsAwesome from "./Components/Profile.bs.js";

function urlToRoute(url) {
  var match = url[/* hash */1];
  if (match === "profile") {
    return /* Profile */1;
  } else {
    return /* Home */0;
  }
}

function App2(Props) {
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = React.useState((function () {
          return urlToRoute(url);
        }));
  var setRoute = match[1];
  React.useEffect((function () {
          Curry._1(setRoute, (function (param) {
                  return urlToRoute(url);
                }));
          return undefined;
        }), /* array */[url[/* hash */1]]);
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, React.createElement("a", {
                      href: "#home"
                    }, "Home"), React.createElement("a", {
                      href: "#profile"
                    }, "Profile")), match[0] ? React.createElement(Profile$ReasonIsAwesome.make, { }) : React.createElement(Home$ReasonIsAwesome.make, { }));
}

var make = App2;

export {
  urlToRoute ,
  make ,
  
}
/* react Not a pure module */
