// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as App2$ReasonIsAwesome from "./App2.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App2$ReasonIsAwesome.make, { }), "app");

export {
  
}
/*  Not a pure module */
