// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Nav$ReasonIsAwesome from "./Components/Nav.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Nav$ReasonIsAwesome.make, { }), "app");

export {
  
}
/*  Not a pure module */
